#!/usr/bin/env python3
# https://github.com/nimadez/mental-diffusion/


from app import *
addon = Addon()


def create_cmd(venv, data, is_short):
    parser = argparse.ArgumentParser()
    _dict = vars(parser.parse_args(namespace=argparse.Namespace(**data)))

    args = ''
    prefix = '-' if is_short else '--'

    for i, key in enumerate(_dict):
        val = _dict[key]

        if is_short:
            if key == 'scheduler': key = 'sc'
            elif key == 'steps': key = 'st'
            elif key == 'strength': key = 'sr'
            elif key == 'lorascale': key = 'ls'
            elif key == 'number': key = 'no'
            elif key == 'preview': key = 'pv'
            elif key == 'lowvram': key = 'lv'
            else: # single char keys
                key = key[0]

        if val != None: # ignore None and False values
            if isinstance(val, bool):
                if val == True:
                    args += f'{prefix}{key}'
            elif isinstance(val, int) or isinstance(val, float):
                args += f'{prefix}{key} {val} '
            else:
                args += f'{prefix}{key} "{val}" '

    return f"{venv} {ROOT_SRC}/mdx.py {args}"


def create_cmd_from_png(venv, img, is_short):
    try:
        metadata = json.loads(Image.open(img).info["MDX"])
        if "version" in metadata: del metadata['version']
        if "pipeline" in metadata: del metadata['pipeline']
        return create_cmd(venv, metadata, is_short)
    except:
        return "Invalid PNG metadata"


def create_json_from_png(venv, img, is_short):
    try:
        metadata = json.loads(Image.open(img).info["MDX"])
        if "version" in metadata: del metadata['version']
        if "pipeline" in metadata: del metadata['pipeline']
        return json.dumps(metadata, indent=4)
    except:
        return "Invalid PNG metadata"


def download_img_no_meta(img):
    if img:
        p = img
        img = Image.open(img)
        data = list(img.getdata())
        img = Image.new("RGB", img.size)
        img.putdata(data)
        fname = Path(p).stem
        addon.download_png(img, fname)


def application(app):
    opt_venv = gr.Textbox(render=False, interactive=True, show_label=False, value="~/.venv/mdx/bin/python3", placeholder="Path to Python venv or bin", max_lines=1)
    opt_short = gr.Checkbox(render=False, interactive=True, label="Short Arguments", value=True)

    out_cmd_metadata = gr.Textbox(render=False, interactive=False, label="Command", placeholder='$', show_copy_button=True, autoscroll=False, lines=3, max_lines=3)
    out_json = gr.Code(render=False, interactive=True, label="JSON Output", language="json")

    with gr.Row():
        with gr.Column():
            in_image = gr.Image(label="MDX-Generated PNG", type="filepath", sources=["upload"], format="png", height=420, elem_classes=["img_contain"])
            with gr.Group():
                with gr.Row():
                    gr.ClearButton(components=[in_image, out_cmd_metadata, out_json], variant="secondary")
                    btn_create = gr.Button("view", variant="primary")
                    btn_create.click(create_cmd_from_png, inputs=[opt_venv, in_image, opt_short], outputs=[out_cmd_metadata])
                    btn_create.click(create_json_from_png, inputs=[opt_venv, in_image, opt_short], outputs=[out_json])
                btn_down = gr.Button("download without metadata")
                btn_down.click(download_img_no_meta, inputs=[in_image])
            opt_venv.render()
            opt_venv.change(create_cmd_from_png, inputs=[opt_venv, in_image, opt_short], outputs=[out_cmd_metadata], show_progress="hidden")
            opt_short.render()
            opt_short.change(create_cmd_from_png, inputs=[opt_venv, in_image, opt_short], outputs=[out_cmd_metadata], show_progress="hidden")
            gr.Examples(examples=[["media/original.png"],["media/example.png"]], inputs=[in_image])

        with gr.Column():
            out_cmd_metadata.render()
            out_json.render()
            gr.HTML(value='<div class="info">Reconstructs mdx.py arguments from PNG images generated by mdx, the exact same image should be created.</div>')


with gr.Blocks(addon.theme) as app:
    app = addon.init_app("Metadata", app)
    addon.draw_app(application)


if __name__== "__main__":
    app.launch()
